### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by Ari100tell** [korczis/osmocom-bb#1]
I want to use [Sourcegraph](https://sourcegraph.com) for osmocom-bb code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/korczis/osmocom-bb. (It should only take 30 seconds.)

Thank you!

**Comment by korczis** [comment]
Sorry for late reply - https://sourcegraph.com/github.com/korczis/osmocom-bb
